title: 'Test site :)'
description: A bold typographic theme inspired by Swiss design.
social_link: discord
social_username: aguynamedjensbot
github_repo: website
github_username: aguynamedjens
theme_color: black
remote_theme: internet-de-france/swiss
baseurl: /website
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
